[versions]
changelog = "2.2.0"
intelliJPlatform = "2.7.0"
kotlin = "2.2.20-Beta2"
kover = "0.9.1"
qodana = "2025.1.1"
firebase-admin = "9.5.0"
junit = "6.0.0-M2"
opentest4j = "1.3.0"

[libraries]
# mistralai-client = { module = "ai.mistral:client", version = "1.0.0" }
# cloudflare-ai = { module = "com.cloudflare:cloudflare-ai", version = "1.0.0" }
mongodb-driver = { module = "org.mongodb:mongodb-driver-sync", version = "4.11.1" }
firebase-admin = { group = "com.google.firebase", name = "firebase-admin", version.ref = "firebase-admin" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
